application:
  allow-get-cards: ${cards.allow-get-cards}

spring:
  application:
    name: cards
  profiles:
    active: production

info:
  app:
    name: "Cards"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'